# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gjJTiUniq3JAN7gKfJ8iqM4rr5O7gZzx3lv3+CRulQc4Eh7yL2jJAV2MXkCUfKCfirJNrVOg1hhbYniNEsueGTnLPmwra0liXtLDaHoIprJOhiNgOwOU1ATO9RfwKKVUEV4eCQJ5heyQ4TB1xBHJcfPd7aNLZe30/w0yaVghHI8HpJjIKQ6jleRxJk7AX1U0HBsV6AnEpQad4O903B2dxYqfa3yYAohDHh/tSm+D1LraA+TsTp2YJPp6c1TNP+fiJ77rhW5E2NBd+6MpyAXe9H3HInT3JQpjk1KYLrEM//Dc8eJX6GCURAc/uDtlmzq+KVI3exgLhv38Kgj+vQACxboOylzCDHaI3XjxQgJ8Qw28mai5hk1ZQgxByL11XOEysWe2rwNu45JHpS9I9p2Hova81ABhD5Yf/bJQIPrcgNaJUDtQY0vaFSA/1Wxkg8AMnl9aNKpzXRYGbxOJleb+U4CpchHBwWx3B7JEC/AJ+QO3E7MEbr4ADVw75XW+kD4b5O1Hr+ml26XqneTmNCi+56KmoLpDwWCr9IUCd8wFfRdNouzuE8sFeBqESawA0Qvb4pxJKO1XZGSZsCEsXc+9WAL2IEVwBrx/3Y/ZjoYIfpb4RY48DxfW9Ls9WYg9C4J3NV6lT8I5jFNKS83swQ6kf5NnlV81FUPJdbtBcJUkBzQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
