travis:
  secure:
    BINSTAR_TOKEN: gjJTiUniq3JAN7gKfJ8iqM4rr5O7gZzx3lv3+CRulQc4Eh7yL2jJAV2MXkCUfKCfirJNrVOg1hhbYniNEsueGTnLPmwra0liXtLDaHoIprJOhiNgOwOU1ATO9RfwKKVUEV4eCQJ5heyQ4TB1xBHJcfPd7aNLZe30/w0yaVghHI8HpJjIKQ6jleRxJk7AX1U0HBsV6AnEpQad4O903B2dxYqfa3yYAohDHh/tSm+D1LraA+TsTp2YJPp6c1TNP+fiJ77rhW5E2NBd+6MpyAXe9H3HInT3JQpjk1KYLrEM//Dc8eJX6GCURAc/uDtlmzq+KVI3exgLhv38Kgj+vQACxboOylzCDHaI3XjxQgJ8Qw28mai5hk1ZQgxByL11XOEysWe2rwNu45JHpS9I9p2Hova81ABhD5Yf/bJQIPrcgNaJUDtQY0vaFSA/1Wxkg8AMnl9aNKpzXRYGbxOJleb+U4CpchHBwWx3B7JEC/AJ+QO3E7MEbr4ADVw75XW+kD4b5O1Hr+ml26XqneTmNCi+56KmoLpDwWCr9IUCd8wFfRdNouzuE8sFeBqESawA0Qvb4pxJKO1XZGSZsCEsXc+9WAL2IEVwBrx/3Y/ZjoYIfpb4RY48DxfW9Ls9WYg9C4J3NV6lT8I5jFNKS83swQ6kf5NnlV81FUPJdbtBcJUkBzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
