appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fZc9AOtBaifemH1d6pSTQkXJgQvRDEtG36mSgCOVcLT6pW7w7Ymbr+4ChzoDySXfPGDMAwWHsfcZlTubxYO2H3ydp8J9lB33+WNcOEb80xZ0dy87ywxcdZyZ7xMDcBAE4C2FwxRhRzTaLDVC9GUXOkpIsCjFSO1EmYL3xjmhp7oiG35aAdiyENn6xEi18ZKaJx/xPfs+fdwHrD3dBjJIb9NtNMxBRS6XZ+U7IPAvcbY4V5qrcJy98daCP1PBockCtE5f5fV/qk4v4gfBS4AGEH3tyYZAhdSE4bkbFnubq4R1UiQGJtm0ByOFpDJJmYYt1A+CtKxD1aRITkrsp8Rz1+XJa5rKwAtLP0NjI9whmyd5gOeJKmNstsf3liaF+hSt7hVg9Q1S65ZVMmTcV5QOYwN0snQBOi4DGBf9YdoDF7aEWrH1Bl2kSAzjEYgMbIeynDdcIBhE9VkZV64502gOVV7Rnee68U2XaYoujQrqVse2q0Ucl0z2iVCIUs7x7rJUZcRjr01lii7ie3Gs+Xo+mMJ+l5rj/Lp0srfj4h3zhqsC6NohUxQnP/R3ududAB5f3ZHMRPCUBDB1p6Js+ZmdKfWddDPjstJ5CNgPyLnug2YmMnt9FqlNWbBhs9Y5aGnO/a2ZHERllXaVj/tQfg5vVELGeQBr01TpSb4ua94eJng=}
conda_forge_output_validation: true
