travis:
  secure:
    BINSTAR_TOKEN: gKLoySsAFA8NbUkMrLVlyMRM1GnGkr5qO5G5FUZqWOnUzD9TNUZnOiHfkAvbyBicy9268RWQmtQviNZIgv5sOpObCaEgIQ2e4/45lSK54VgZyUFmt9p56zXqUQhI8gFz7s4GQDTlIT1tIQzEzO4ShHcNRl4Q90H4+5Uz+5FtxxCKQpAIDlARpnRv8drqMTrIJU7dBYmtLJ5aNeoG9oQBY/0dWjOKZI7ez2DYHn+kPIEOJ7llixB1quoUoohQWgXLwuUDsDNl4+awGXPYt5nSw7PQnrFUzQfQcQDtCkMwmaup20cEJLX0/5uVISKgCGakihk+Qm9cnBDsY3qkc3feUmAmD9OVQnQqL5F4nhwIR0jCaO2PNmb7WnYe+t5ZqL9Cv3iReKzdpoqr2aNE6i22+RDJ47V9fIdrb9/jQbkX3YedK47jbz7g4Y/a6jeuGumsN5CZzYTEtq2xfUfM9wpEtnAr5clcz/zdLCP2OvX8IG90pf1DxRCO1ZqqYN3is0WwEpyEBWzhDw2OVuuzi3b4J0o6bbADjFE0IE+VSYO4rs07mFvGzqy/4MYSxKqF3qOzCcCkNY7czbS49/L+MzuxOY75iiYl4Je/BGq64GNhH/a2Id7yPle9on0x9Pc9wfmCHLV7lfrVjEwnh2Y+eCFVvvNIhvxDOZO0DHmX4MdtyKM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
